# -*- Makefile -*-

all: A2q1a A2q1b A2q2a A2q2b stack queue A2q3 A2q5

A2q1a:
	gcc A2q1a.c -o A2q1a

A2q1b:
	gcc A2q1b.c -o A2q1b

A2q2a:
	gcc A2q2a.c -o A2q2a

A2q2b:
	gcc A2q2b.c -o A2q2b

stack:
	gcc stack.c -o stack

queue:
	gcc queue.c -o queue

A2q3:
	gcc A2q3.c -o A2q3

A2q5:
	gcc A2q5.c -o A2q5